
[dialogs]
confirm = "Confermi?"
error   = "Errore"
ok      = "Ok"
cancel  = "Annulla"

[dialogs.chapter]
add    = "Aggiungi paragrafo"
edit   = "Modifica paragrafo"
delete = "Il paragrafo “%1” verrà eliminato"
exist  = "Questo paragrafo esiste già"

name         = "Key"
title        = "Titolo"
group        = "Gruppo"
genericFlags = "Inserisci qui altri indicatori di cui hai bisogno, uno per riga"

[dialogs.chapter.warnings]
duplicate    = "Esiste un'altro paragrafo con la stessa key!"
invalidkey   = "Key dovrebbe contenere solo caratteri alfanumerici (a-z, A-Z, 0-9)"
invalidgroup = "Gruppo dovrebbe contenere solo caratteri alfanumerici (a-z, A-Z, 0-9)"


[dialogs.newbook]
new    = "Crea un nuovo Libro"
title  = "Titolo"
author = "Autore"
hint   = "Puoi recuperare il libro precedente da <b>File -> Sessioni recenti</b>"

[dialogs.newfirebook]
new    = "Crea o accedi a un Libro Collaborativo"
book   = "Nome libro"
getStarted = """Con questa funzione puoi collegare Magebook al tuo account Google, così da creare libri che si possono modificare in simultanea, proprio come i Documenti Google.<br>Prima di iniziare, dovrai collegare Magebook al tuo account <a target="_blank" href="https://librogamesland.github.io/magebook/#/?id=progetti-collaborativi">seguendo questa guida</a>."""

[dialogs.remap]
group      = "Filtro gruppi"
flags      = "Escludi simboli"
savecopy   = "Salva una copia"

[dialogs.remap.shuffle]
title      = "Rimescola"
hint       = "Rimescola i paragrafi con chiave numerica. Puoi scegliere di mescolare solo i paragrafi che fanno parte di alcuni gruppi, o di escludere i paragrafi con determinati simboli. Per sicurezza, dovresti salvare una copia del libro prima di mescolare."

[dialogs.remap.sort]
title      = "Riordina"
hint       = "I paragrafi saranno spostati così da rispettare l'ordine di numero."

[dialogs.remap.compact]
title      = "Compatta"
hint       = "I paragrafi verranno rinominati in modo da avere numeri consecutivi, senza buchi in mezzo."


[dialogs.lock]
title      = "Attenzione"
text       = "Un'altra tab ha modificato i dati di questa sessione. Se sovrascrivi, quei cambiamenti verranno persi. Se vuoi mantenere entrambe le versioni, puoi creare una nuova sessione e recuperare quella vecchia con <br><b>File -> Sessioni recenti</b>."
new        = "Apri nuova sessione"
overwrite  = "Sovrascrivi"

[dialogs.graph]
loading    = "Caricamento grafo..."
open       = "Apri un una nuova pagina"
download   = "Download (immagine .svg)"


[navbar.file]
title       = "File"
new         = "Nuovo"
newFire     = "Nuovo collaborativo"
share       = "Condividi"
open        = "Apri/importa LGC..."
save        = "Salva"
recover     = "Sessioni recenti"
recoverFire = "Sessioni collaborative"

[navbar.book]
title   = "Libro"
graph   = "Visualizza grafico"
shuffle = "Rimescola"
sort    = "Riordina paragrafi"
compact = "Compatta paragrafi"

[navbar.export]
title = "Esporta"
docx  = "Word (.docx)"
fodt  = "Libreoffice (.fodt)"
html  = "Sito web (.html)"
xlgc  = "LibroGameCreator 3"
json  = "Json"
advanced = "Webapp avanzata"


others       = "Altri (ebook, app Android, ...)"
otherslink   = "https://librogamesland.github.io/magebook/index.html#/?id=altri-formati"
settings     = "Opzioni esportazione"
settingslink = "https://librogamesland.github.io/magebook/index.html#/?id=opzioni"

[navbar.help]
title     = "Aiuto"
guide     = "Guida"
guidefile = "https://librogamesland.github.io/magebook"
forum     = "Forum Lgl"
report    = "Segnala bug/suggerisci feature"
about     = "Info"

[navbar.buttons]
fullscreen = "Schermo intero"
darktheme  = "Cambia tema scuro/chiaro"


[sidemenu]
toggle    = "Apri menu laterale"
chapters  = "Paragrafi"
allgroup  = "Tutti i paragrafi"
allgrouperrors  = "Senza entrata/uscita"
allgrouporphanlinks  = "Con link errati"
linkshere = "Link al par."

[sidemenu.actions]
goback   = "Vai indietro"
add      = "Aggiungi entità (ctrl+R)"
edit     = "Modifica entità (ctrl+E)"
delete   = "Elimina entità (ctrl+D)"


[editor.buttons]
find = "Cerca (ctrl+F)"
undo = "Annulla ultimo cambiamento (ctrl+Z)"
redo = "Ripristina ultimo cambiamento (ctrl+shift+Z)"
quicklink  = "Link al primo paragrafo disponibile (ctrl+K)"
link  = "Aggiungi link (ctrl+L)"

[editor]
chars = "caratteri"


[about]
contact = "Contattami"
text = """
Magebook è un editor di librogame sviluppato da <b>Luca Fabbian</b> con il supporto della community di Lgl."""


[books]
local = """
# Titolo
author: Nome e Cognome


### 1
Esempio di paragrafo. Puoi modificarlo sfruttando i tasti a destra.
Questo è un link verso il paragrafo [2]. I link possono essere anche nel formato esteso [Testo](#paragrafo), dove Testo è opzionale.


### Paragrafo con titolo {#2}
Questo è il secondo paragrafo. I paragrafi possono contenere anche testo in *corsivo* o **grassetto**.  Puoi anche usare <b>grassetto</b>, <i>corsivo</i>, o <u>sottolineato</u>. Aggiungi commenti con ` `, ad esempio `NOTA: devo rivedere questo paragrafo`.
"""
fire = """
# %1
author: Nome e Cognome


### 1
Questo è un libro collaborativo memorizzato sul tuo account Google e che può essere modificato da più persone contemporaneamente. Salva questa pagina fra i segnalibri del tuo browser e inviala a chi vuoi, vedrai le modifiche sincronizzate in tempo reale.
"""

[app]
openlocal    = "Crea o apri file"
openfire     = "Crea o accedi a un libro collaborativo"
chooseother  = "Apri un altro"

[dialogs.version]
title = "Nuova versione - "
text  = 'Scopri di più nella <a ref="_blank" href="https://librogamesland.github.io/magebook/#/?id=versioni">guida</a>.'
"1.0" = "Versione iniziale."
"1.1" = "Aggiunto formato link corto [numero] e opzione 'disableShortLinks: true'.<br>I link a paragrafi inesistenti vengono segnalati nel menu laterale.<br>Restyle dell'interfaccia.<br>Aggiunta esportazione sito web.<br>Correzioni varie."
"1.2" = "Ristrutturazione massiccia del codice interno.<br>L'editor adesso è basato su Codemirror6 anziché Ace. Dovrebbe risultare più veloce, bello e più mobile friendly.<br>Nuove impostazioni e Opzioni esportazione come renameLink, page, textFont, ...<br>Adesso 'Sessioni recenti' tiene traccia anche dei progetti collaborativi."
